#!/bin/bash
# shellcheck disable=SC1117

FINISHED_DIR=""
# Sub-directories to exclude
EXCLUSIONS=()

ORANGE="\e[1;38;5;166m"
GREEN="\e[1;38;5;40m"
BLUE="\e[1;38;5;38m"
FONT_RESET="\e[0m"

LAST_LOGIN_TIME=$(last --time-format iso "$USER" | grep -v still | head -1 | awk '{print $6}')
if [ -z "$LAST_LOGIN_TIME" ]; then
	LAST_LOGIN_TIME=$(last -f /var/log/wtmp.1 --time-format iso "$USER" | grep -v still | head -1 | awk '{print $6}')
fi

OLD_IFS=$IFS

[ -L $FINISHED_DIR ] && DIR=$FINISHED_DIR"/" || DIR=$FINISHED_DIR

EXCLUDE=()
IFS=' '
for EXCLUSION in "${EXCLUSIONS[@]}"; do
	EXCLUDE+=( "-not" "-path" "${FINISHED_DIR}/${EXCLUSION}" )
done

FILES=()
while IFS= read -r -d '' FILE; do
	if echo "$FILE" | grep -q "+$(basename "$FINISHED_DIR")$"; then
		continue
	fi
	FILES+=( "$FILE" )
done < <(find $DIR -maxdepth 1 "${EXCLUDE[@]}" -newerct "$LAST_LOGIN_TIME" -printf '%T@+%f\0')

if [[ ${#FILES} == 0 ]]; then
	echo -e "${ORANGE}No new downloads since last login.${FONT_RESET}\n"
else
	echo -e "${GREEN}New downloads since last login:${FONT_RESET}\n"
	for FILE in "${FILES[@]}"; do
		read -r d f <<<"$(echo "$FILE" | sed -r 's/([0-9.]+)\+(.*)/\1 \2/')"
		echo -e "$(date -d "@$d" "+%Y-%m-%d %H:%M") -> ${BLUE}${f}${FONT_RESET}"
	done
fi

IFS=$OLD_IFS
